name: Deploy Frontend to Test Env

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend application
        run: |
          touch .env
          echo ${{ vars.env }} > .env
          cat .env
          npm run build

      - name: Upload files to Server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          # port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.SSH_SECRET_KEY }}
          localPath: './dist'
          remotePath: ${{ secrets.REMOTE_PATH }}